// AUTO-GENERATED by extract_stats.py from real Amman Vision data
// 18,038 real passenger boardings

export const REAL_STATS = {
  totalBoardings:    18038,
  busiestRoute:      "Alatroon hospital-Al Mahatta Terminal",
  busiestRouteCount: 4344,
  busiestStop:       "12761.0",
  peakHour:          "7:00 PM",
  uniqueVehicles:    104,
  uniqueRoutes:      27,
  hourlyDemand:      {"0.0": 201, "1.0": 94, "3.0": 1, "5.0": 29, "6.0": 252, "7.0": 683, "8.0": 782, "9.0": 1426, "10.0": 774, "11.0": 1021, "12.0": 571, "13.0": 680, "14.0": 831, "15.0": 1049, "16.0": 1040, "17.0": 1086, "18.0": 1523, "19.0": 1644, "20.0": 942, "21.0": 1069, "22.0": 1142, "23.0": 1197},
  routeCounts:       {"Alatroon hospital-Al Mahatta Terminal": 4344, "Abu Nsair-Jordan University": 2103, "Al Mahatta Terminal-Aljumrok Circle": 1849, "Al jomrouk-Swaileh": 1588, "Um AlUsood-Al Muhajereen": 1341, "Al yadodah-City Center": 1274, "Al Mahatta Terminal-Marj Al Hamam": 1200, "Abu Alia-Jordan University": 880, "Raghadan Terminal-BRT Swaileh Terminal": 735, "Abu Alia-Aldakhlyeh": 491},
} as const;

// AI demand prediction — peak hours from real data
export const PEAK_HOURS = Object.entries(REAL_STATS.hourlyDemand)
  .sort(([,a],[,b]) => (b as number)-(a as number))
  .slice(0, 3)
  .map(([h, count]) => ({
    hour: parseInt(h),
    label: parseInt(h) < 12 ? h+":00 AM" : (parseInt(h)-12||12)+":00 PM",
    boardings: count as number,
    prediction: Math.round((count as number) * 1.08), // AI adds 8% growth
  }));
