"""
SmartTransit — KML to GeoJSON Converter
Run: python kml_to_geojson.py
Converts your 5 KML route files into routes_data.ts for the React map.
"""

import os
import json
import re
import sys
import glob

print("=" * 55)
print("  SmartTransit — KML Route Converter")
print("=" * 55)

# Route colors matching the app design system
ROUTE_COLORS = [
    '#00C896',  # teal   — Route 1
    '#FF6B35',  # orange — Route 2
    '#3B9EFF',  # blue   — Route 3
    '#A78BFA',  # purple — Route 4
    '#FF9F43',  # amber  — Route 5
]

def parse_kml(filepath):
    """Extract coordinates from KML file without external dependencies."""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    # Extract name
    name_match = re.search(r'<name[^>]*>(.*?)</name>', content, re.DOTALL)
    name = name_match.group(1).strip() if name_match else os.path.basename(filepath).replace('.kml','')
    name = re.sub(r'<[^>]+>', '', name).strip()

    # Extract all coordinate blocks
    all_coords = []
    coord_blocks = re.findall(r'<coordinates[^>]*>(.*?)</coordinates>', content, re.DOTALL)

    for block in coord_blocks:
        block = block.strip()
        # KML format: lon,lat,elevation or lon,lat
        points = []
        for token in block.split():
            parts = token.strip().split(',')
            if len(parts) >= 2:
                try:
                    lon, lat = float(parts[0]), float(parts[1])
                    # Sanity check — Jordan coordinates
                    if 34.0 < lon < 40.0 and 29.0 < lat < 34.0:
                        points.append([lon, lat])
                except ValueError:
                    continue
        all_coords.extend(points)

    return name, all_coords

# Find KML files
print("\n[1/3] Searching for KML files...")
kml_files = []

# Search current dir and parent dirs
for pattern in ['*.kml', '**/*.kml', '../*.kml', '../../*.kml']:
    found = glob.glob(pattern, recursive=True)
    kml_files.extend(found)

kml_files = list(set(kml_files))

if not kml_files:
    print("  ⚠  No KML files found automatically.")
    print("  Enter the folder path containing your KML files:")
    folder = input("  > ").strip().strip('"')
    kml_files = glob.glob(os.path.join(folder, '*.kml'))

if not kml_files:
    print("  ✗ Still no KML files found. Check the path and try again.")
    sys.exit(1)

print(f"  Found {len(kml_files)} KML file(s):")
for f in kml_files:
    print(f"    • {f}")

# Parse each KML
print("\n[2/3] Parsing KML files...")
routes = []
for i, filepath in enumerate(sorted(kml_files)):
    name, coords = parse_kml(filepath)
    if len(coords) < 2:
        print(f"  ⚠  {filepath}: only {len(coords)} coordinates — skipping")
        continue

    color = ROUTE_COLORS[i % len(ROUTE_COLORS)]
    routes.append({
        'id': i + 1,
        'name': name,
        'color': color,
        'coordinates': coords,
        'stop_count': max(2, len(coords) // 10),
    })
    print(f"  ✓ {name}: {len(coords)} coordinate points → color {color}")

if not routes:
    print("  ✗ No valid routes found in KML files.")
    sys.exit(1)

# Generate TypeScript
print("\n[3/3] Generating routes_data.ts...")

# Build coordinate arrays as TS
coord_arrays = []
for r in routes:
    coords_str = ', '.join(f'[{c[1]:.6f}, {c[0]:.6f}]' for c in r['coordinates'])
    coord_arrays.append(f'''  {{
    id: {r['id']},
    name: "{r['name']}",
    color: "{r['color']}",
    coordinates: [{coords_str}] as [number,number][],
  }}''')

ts = f'''// AUTO-GENERATED by kml_to_geojson.py from real KML route files
// {len(routes)} routes from Amman Vision data

export const KML_ROUTES = [
{',\n'.join(coord_arrays)}
];

// Center of all routes (for map centering)
export const ROUTES_CENTER: [number, number] = [
  {sum(r['coordinates'][len(r['coordinates'])//2][1] for r in routes) / len(routes):.6f},
  {sum(r['coordinates'][len(r['coordinates'])//2][0] for r in routes) / len(routes):.6f},
];

// Bounds for fitting map view
const allLats = [{', '.join(str(round(c[1],4)) for r in routes for c in r['coordinates'][:5])}];
const allLons = [{', '.join(str(round(c[0],4)) for r in routes for c in r['coordinates'][:5])}];
export const ROUTES_BOUNDS = {{
  minLat: Math.min(...allLats),
  maxLat: Math.max(...allLats),
  minLon: Math.min(...allLons),
  maxLon: Math.max(...allLons),
}};
'''

with open('routes_data.ts', 'w', encoding='utf-8') as f:
    f.write(ts)

# Also save GeoJSON for reference
geojson = {
    'type': 'FeatureCollection',
    'features': [
        {
            'type': 'Feature',
            'properties': {'name': r['name'], 'color': r['color'], 'id': r['id']},
            'geometry': {'type': 'LineString', 'coordinates': r['coordinates']},
        }
        for r in routes
    ]
}
with open('routes.geojson', 'w') as f:
    json.dump(geojson, f)

print(f"  ✓ Saved routes_data.ts ({len(routes)} routes)")
print(f"  ✓ Saved routes.geojson")

print("\n" + "=" * 55)
print("  DONE! Copy routes_data.ts to:")
print("  src/lib/routes_data.ts")
print("=" * 55)
print(f"""
  ROUTES EXTRACTED:
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━""")
for r in routes:
    print(f"  {r['name']}: {len(r['coordinates'])} points")
print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
